### ISSUE TITLE
Handle error events

### ISSUE THREAD

**Issue by valeriansaliou** [Scan0815/browser-video-thumbnail-generator#1]
Thank you for this library!

I've noticed that if you try to generate a thumbnail from a video that's unsupported by the browser, say from a H265 MP4 file on Firefox, the Promise will hang forever, since there's no error handler within the library.

Adding this code:

```js
this.video.addEventListener("error", () => {
  reject(
    new Error(
      "Error loading video (codec might not be supported by this browser)"
    )
  );
});
```

In the following locations:

- https://github.com/Scan0815/browser-video-thumbnail-generator/blob/main/src/libs/videoThumbnailGenerator.ts#L84
- https://github.com/Scan0815/browser-video-thumbnail-generator/blob/main/src/libs/videoThumbnailGenerator.ts#L60

Addresses the issue.

**Comment by Scan0815** [comment]
Hi, thx for the improvement. 
I add it to the package.

cheers Oliver
