### ISSUE TITLE
Grey image on iOS

### ISSUE THREAD

**Issue by jparismorgan** [Scan0815/browser-video-thumbnail-generator#2]
Hi there, when I run on iOS I end up with a blank image and no errors - curious if you also have run into this and have any suggestions on how to fix? Thank you!

Here is a sample result:

![IMG_8474_preview](https://github.com/Scan0815/browser-video-thumbnail-generator/assets/1396242/1082241a-9b15-4309-8e35-a7f7156f3376)

**Comment by Scan0815** [comment]
hi, thank you for the issue. 
On Safari its need a bit longer to grab the image. 
I made a fix in the next build. 
I release it today. 
Cheers THX.

**Comment by Scan0815** [comment]
Release is online @jparismorgan please test it and check if it now work. thx

**Comment by Scan0815** [comment]
@jparismorgan work it? like you expected

**Comment by jparismorgan** [comment]
Hi yes, it's working great, thank you!
